Fix env.yml
remove the last line '-e .' because this repo is not a package.
add wandb and hydra-core.
remove the version for transformers because current version will cause "ImportError: cannot import name 'CLIPImageProcessor' from 'transformers'"